basic neuron

In [4]:
import numpy as np
inputs = [2,4,7]
weights = [.3,.5,-.2]
bias=2

output = np.dot(inputs,weights)
output+=bias

print(output)

3.2


ReLU Activation

In [6]:
# y=max(0,x)


Y= max(0,output)
print(output)

3.2


Random initalization using numpy of weights

In [18]:
inputs = np.random.randint(0,10,3)
weights = np.random.random(3) #random decimal
bias=10
print(inputs,weights,bias)
output = np.dot(inputs,weights)+bias
print(output)

[5 1 5] [0.03200968 0.90605185 0.66321714] 10
14.382185963781485


A layer

In [32]:
weights = np.random.random((4,3)) # matrix
print(weights)
biases = np.random.randint(0,5,4)
print(inputs)
print(inputs.shape,weights.shape)

output = np.dot(inputs,weights.T)+biases #.T because row but match column
print("outputs:",output)

[[0.89122792 0.30939651 0.96908923]
 [0.16275383 0.87526484 0.19462727]
 [0.46061877 0.39556569 0.65574359]
 [0.08471699 0.73944593 0.89186392]]
[5 1 5]
(3,) (4, 3)
outputs: [11.61098225  2.66217033  9.97737753  6.6223505 ]


2 Layer

In [34]:
inputs = np.random.randint(0,10,3) # inputs
weights1 = np.random.random((4,3)) # matrix  4 neurons, 3 weights each
biases1 = np.random.randint(0,5,4) #biases for each neuron in layer1

output1 = np.dot(inputs,weights1.T)+biases1 #.T because row but match column
print(output1) # four outputs


weights2 = np.random.random((3,4))
biases2 = np.random.randint(0,5,3)

output2 = np.dot(output1,weights2.T) + biases2
print(output2)


[ 4.39911841  6.75378191  8.86654335 11.19241142]
[14.3293691  17.15049731 16.13372958]


3 inputs Neurons--> 4 hidden Neurons --> 3 output neurons

In [44]:
class Layer:
  def __init__(self,n_inputs,n_neurons):
    self.weights = np.random.random((n_neurons,n_inputs))
    self.biases = np.random.randint(0,10,n_neurons)
  def forward(self,inputs):
    self.output=np.dot(inputs,self.weights.T) + self.biases



inputs = [1,2,3]
layer1 = Layer(3,4)

layer1.forward(inputs)
print(layer1.output)

#print(len(layer1.output))

layer2 = Layer(len(layer1.output),3)
layer2.forward(layer1.output)
print(layer2.output)

[11.99496842 11.78337054  8.70343701  5.86013695]
[21.00902454 24.33457984 25.12718368]


For bath of inputs

In [46]:
inputs =np.array([[1,2,3],
         [2,3,4],
         [3,4,5]])
print(inputs.shape)

(3, 3)


In [47]:
weights = np.random.random((4,3))
biases= [2,3,4,5]

output = np.dot(inputs,weights.T) + biases
print(output)

[[ 5.8714255   6.2555995   7.64553697  8.01505445]
 [ 7.49719032  7.66944853  9.38217481  9.90011093]
 [ 9.12295514  9.08329756 11.11881265 11.78516741]]


TF Keras From NerualNine


In [4]:
from re import X
import cv2
import numpy as np
import matplotlib.pyplot as plt
import tensorflow as tf


mnist = tf.keras.datasets.mnist

(x_train,y_train), (x_test, y_test) = mnist.load_data()


#normalize image
#0-255 --> 0-1 brightness

x_train = tf.keras.utils.normalize(x_train,axis=1)
x_test=tf.keras.utils.normalize(x_test,axis=1)

model = tf.keras.models.Sequential()
model.add(tf.keras.layers.Flatten(input_shape=(28,28)))
model.add(tf.keras.layers.Dense(128,activation='relu'))
model.add(tf.keras.layers.Dense(128,activation='relu'))
model.add(tf.keras.layers.Dense(10,activation='softmax'))

model.compile(optimizer='adam', loss='sparse_categorical_crossentropy',metrics=[
    'accuracy'
])
model.fit(x_train,y_train, epochs=3)

Epoch 1/3
1875/1875 [==============================] - 12s 6ms/step - loss: 0.2705 - accuracy: 0.9201
Epoch 2/3
1875/1875 [==============================] - 6s 3ms/step - loss: 0.1119 - accuracy: 0.9656
Epoch 3/3
1875/1875 [==============================] - 8s 4ms/step - loss: 0.0757 - accuracy: 0.9764


In [5]:
loss, accuracy = model.evaluate(x_test,y_test)
print(loss)
print(accuracy)

313/313 [==============================] - 1s 2ms/step - loss: 0.1034 - accuracy: 0.9679
0.10337936878204346
0.9678999781608582


Mnist pytorch from NerualNine

In [24]:
import torchvision
from torchvision import datasets
from torchvision.transforms import ToTensor

In [25]:
train_data=datasets.MNIST(
    root= 'data',
    train=True,
    transform = ToTensor(),
    download = True
)
test_data=datasets.MNIST(
    root= 'data',
    train=False,
    transform = ToTensor(),
    download = True
)

Failed to download (trying next):
HTTP Error 403: Forbidden



100%|██████████| 9912422/9912422 [00:00<00:00, 58135001.28it/s]


Extracting data/MNIST/raw/train-images-idx3-ubyte.gz to data/MNIST/raw

Failed to download (trying next):
HTTP Error 403: Forbidden



100%|██████████| 28881/28881 [00:00<00:00, 1852142.77it/s]

Extracting data/MNIST/raw/train-labels-idx1-ubyte.gz to data/MNIST/raw



Failed to download (trying next):
HTTP Error 403: Forbidden



100%|██████████| 1648877/1648877 [00:00<00:00, 13310977.49it/s]


Extracting data/MNIST/raw/t10k-images-idx3-ubyte.gz to data/MNIST/raw

Failed to download (trying next):
HTTP Error 403: Forbidden



100%|██████████| 4542/4542 [00:00<00:00, 3499362.37it/s]

Extracting data/MNIST/raw/t10k-labels-idx1-ubyte.gz to data/MNIST/raw



In [30]:
from torch.utils.data import DataLoader

loaders = {
    'train': DataLoader(train_data,
                        batch_size=100,
                        shuffle=True,
                        num_workers=1),

        'test': DataLoader(test_data,
                        batch_size=100,
                        shuffle=True,
                        num_workers=1),
}

In [31]:
loaders

{'train': <torch.utils.data.dataloader.DataLoader at 0x7ae34a6bba60>,
 'test': <torch.utils.data.dataloader.DataLoader at 0x7ae34a6baaa0>}

In [ ]:
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim

class CNN(nn.M)